### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by benoitjy** [drdada/Fail2banTools#1]
Salut,

Je tente en français, j'ai cru comprendre que ça peut aller... ;-)
Lorsque je tente l'utilisation des scripts, j'ai un message systématique:
`./stats.sh: line 13: $: command not found`
et la ligne en question:
`grep "Ban " /var/log/fail2ban.log | grep `date +%Y-%m-%d` | awk '{print $NF}' | sort | awk '{print $1,"("$1")"}' | logresolve |$`
Je ne suis pas du tout en capacité de comprendre finement la ligne, aussi, je sèche sur le problème... Auriez-vous une idée pour solutionner mon problème?
Merci

BJ

**Comment by drdada** [comment]
Salut, 
C'est corrigé.
Ca devrait fonctionner

https://github.com/drdada/Fail2banTools/commit/76f6229df8e104e7b3cdd57b18e7eb9c3ea83836

**Comment by benoitjy** [comment]
Super, ça marche. Merci!
